# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43e7e23833202407398bd617f8a3ed5a3b3bd4d3681584e2154dcf1d8d0199f12b7cffc5648ab0ccfc4353fe2015651f918b55b98b24606555302e714bd33d06

test:
  secret_key_base: 5ac96c8bb45b128d5f257df51da026dba771a10726fc68887672b55b9215b08f131a6a001f2d27c063333f7d93ce443fdbb70877c8839af08c7e436df8a90de4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
